---USER LOGIN
CREATE TABLE users (
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL CHECK (LENGTH(password) >= 8)
);
INSERT INTO users (username, password) VALUES ('Maham', 'stringpw');
INSERT INTO users (username, password) VALUES ('Alina', 'strongpw');
--ADMIN LOGIN
CREATE TABLE admin (
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL CHECK (LENGTH(password) >= 8)
);

INSERT INTO admin (username, password) VALUES ('Admin', '123string');
INSERT INTO admin (username, password) VALUES ('Admin', '127strong');


--VIEW FOR START PAGE----
select * from starttable;
CREATE TABLE starttable (
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);
INSERT INTO starttable (username, password, role) VALUES ('Alina', '123', 'USER');
INSERT INTO starttable (username, password, role) VALUES ('Maham', 'password2', 'USER');
INSERT INTO starttable (username, password, role) VALUES  ('Admin', '123', 'ADMIN');
 INSERT INTO starttable (username, password, role) VALUES ('Admin', 'password2', 'ADMIN');
 
CREATE VIEW userview AS
SELECT username, role
FROM starttable
WHERE role = 'USER';
CREATE VIEW adminview AS
SELECT username, role
FROM starttable
WHERE role = 'ADMIN';








--RECIPIENT INFO USING STORED PROCEDURE-----
CREATE TABLE Recipients (
    recipient_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    contact VARCHAR2(20) NOT NULL,
    email_address VARCHAR2(100) NOT NULL,
    age NUMBER NOT NULL,
    gender VARCHAR2(10) NOT NULL,
    blood_type VARCHAR2(5) NOT NULL,
    PRIMARY KEY (recipient_id)
);

CREATE OR REPLACE PROCEDURE ADD_RECIPIENT(
    p_full_name VARCHAR2,
    p_address VARCHAR2,
    p_contact VARCHAR2,
    p_email_address VARCHAR2,
    p_age NUMBER,
    p_gender VARCHAR2,
    p_blood_type VARCHAR2
)
AS
BEGIN
    INSERT INTO Recipients (full_name, address, contact, email_address, age, gender, blood_type)
    VALUES (p_full_name, p_address, p_contact, p_email_address, p_age, p_gender, p_blood_type);
    COMMIT;
END ;

BEGIN
    ADD_RECIPIENT('Mohammed Ali', '456 Oak St', '555-5678', 'mohammed.ali@email.com', 30, 'Male', 'B+');
    ADD_RECIPIENT('Fatima Khan', '789 Pine St', '555-6789', 'fatima.khan@email.com', 28, 'Female', 'A-');
    ADD_RECIPIENT('Ahmed Hassan', '101 Cedar St', '555-7890', 'ahmed.hassan@email.com', 35, 'Male', 'O+');
    ADD_RECIPIENT('Aisha Malik', '202 Maple St', '555-8901', 'aisha.malik@email.com', 25, 'Female', 'AB-');
    ADD_RECIPIENT('Yusuf Ahmed', '303 Birch St', '555-9012', 'yusuf.ahmed@email.com', 40, 'Male', 'A+');
END;
--EDIT MODIIFYING DATA--
ALTER TABLE Recipients
MODIFY (full_name VARCHAR2(100) ,
        address VARCHAR2(255) ,
        contact VARCHAR2(20),
        email_address VARCHAR2(100) ,
        age NUMBER ,
        gender VARCHAR2(10) ,
        blood_type VARCHAR2(5) );

        
    CREATE OR REPLACE PROCEDURE UPDATE_RECIPIENT(
    p_recipient_id NUMBER,
    p_full_name VARCHAR2,
    p_address VARCHAR2,
    p_contact VARCHAR2,
    p_email_address VARCHAR2,
    p_age NUMBER,
    p_gender VARCHAR2,
    p_blood_type VARCHAR2
)
AS
BEGIN
    UPDATE Recipients
    SET 
        full_name = p_full_name,
        address = p_address,
        contact = p_contact,
        email_address = p_email_address,
        age = p_age,
        gender = p_gender,
        blood_type = p_blood_type
    WHERE recipient_id = p_recipient_id;

    COMMIT;
END;
BEGIN
    UPDATE_RECIPIENT(1, 'Updated Name', 'Updated Address', 'Updated Contact', 'Updated Email', 25, 'Updated Gender', 'Updated Blood Type');
END;


CREATE OR REPLACE PROCEDURE DELETE_RECIPIENT (
    p_recipient_id IN NUMBER
) AS
BEGIN
    DELETE FROM Recipients WHERE recipient_id = p_recipient_id;
    COMMIT;
END DELETE_RECIPIENT;


select * from Recipients;







--CONTACT US---
CREATE TABLE ContactUsForm (
    name VARCHAR(255),
    email VARCHAR(255),
    message VARCHAR(255)
);
select * from ContactUsForm;


--BLOOD STOCK PAGE---
CREATE TABLE BloodStock (
    BloodGroup VARCHAR(10) PRIMARY KEY,
    PerUnit INT
);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('A+', 10);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('A-', 15);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('B+', 20);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('B-', 25);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('AB+', 30);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('AB-', 35);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('O+', 40);
INSERT INTO BloodStock (BloodGroup, PerUnit) VALUES('O-', 45);


